language: python
python:
  - "2.7"
install:
 - pip install tox
 - pip install -r requirements.txt
script:
 - tox
env:
 - TOXENV=py27-django14
 - TOXENV=py27-django18
 - TOXENV=py27-django19
 - TOXENV=py27-django110
 - TOXENV=py35-django18
 - TOXENV=py35-django19
 - TOXENV=py35-django110
